### ISSUE TITLE
Nullpointer on convert record from jsonld to marc

### ISSUE THREAD

**Issue by sweco-semhul** [libris/librisxl#129]
Trying to POST following record to http://localhost:8180/_convert

```
{"@graph": [{"marc:encLevel": {"@id": "marc:MinimalLevel"}, "marc:originalCatalogingAgency": {"@id": "http://127.0.0.1:5000/some?type=Organization&name=SHB"}, "created": "2002-08-20T00:00:00.0+02:00", "sameAs": [{"@id": "http://libris.kb.se/bib/8550505"}], "@id": "http://127.0.0.1:5000/h0sq1hct3kbklw0", "controlNumber": "8550505", "marc:catalogingSource": {"@id": "marc:CooperativeCatalogingProgram"}, "modified": "2004-04-20T09:39:04.0+02:00", "marc:linked": {"@id": "marc:RecordHasLinks-Obsolete"}, "mainEntity": {"@id": "http://127.0.0.1:5000/h0sq1hct3kbklw0#it"}, "@type": "Record", "marc:catForm": {"@id": "marc:Aacr2"}}, {"instanceOf": {"@id": "http://127.0.0.1:5000/h0sq1hct3kbklw0#work"}, "hasTitle": {"mainTitle": "Den postsovjetiske Karl XII", "@type": "InstanceTitle"}, "bibliography": [{"@id": "http://127.0.0.1:5000/some?type=Organization&notation=SHB"}], "publication": [{"date": "2001"}], "sameAs": [{"@id": "http://libris.kb.se/resource/bib/8550505"}], "issuanceType": "ComponentPart", "responsibilityStatement": "av Aleksander Kan", "publicationCountry": [{"@id": "https://id.kb.se/country/sw"}], "isPartOf": [{"@id": "http://127.0.0.1:5000/some?type=Aggregate&title=Karolinska%20f%C3%B6rbundets%20%C3%A5rsbok&issn=0348-9833&describedBy.type=Record&describedBy.id=http%3A%2F%2Flibris.kb.se%2Fbib%2F8261779&describedBy.controlNumber=8261779&part=2000%2C%20s.%20%5B215%5D-217"}], "@id": "http://127.0.0.1:5000/h0sq1hct3kbklw0#it", "@type": "Instance"}, {"@graph": {"classification": [{"@id": "https://id.kb.se/term/kssb/7/Kc.428"}], "language": [{"@id": "https://id.kb.se/language/swe"}], "qualifiedAttribution": [{"@type": "marc:MainEntry", "agent": {"@id": "http://127.0.0.1:5000/some?type=Person&familyName=Kan&givenName=Aleksandr%20Sergeevi%C4%8D&birthYear=1925"}}], "@id": "http://127.0.0.1:5000/h0sq1hct3kbklw0#work", "@type": "Text", "subject": [{"@id": "http://127.0.0.1:5000/some?type=Concept&focus.type=Person&focus.name=Karl&focus.numeration=XII%2C&focus.qualifyingNote=kung%20av%20Sverige%2C&focus.birthYear=1682&focus.deathYear=1718"}]}}, {"@graph": {"@id": "http://127.0.0.1:5000/some?type=Organization&name=SHB", "@type": "Organization", "name": "SHB"}}, {"@graph": {"@id": "http://127.0.0.1:5000/some?type=Organization&notation=SHB", "@type": "Organization", "notation": "SHB"}}, {"@graph": {"inScheme": {"@id": "https://id.kb.se/term/kssb/7"}, "@id": "https://id.kb.se/term/kssb/7/Kc.428", "@type": "Concept", "notation": "Kc.428"}}, {"@graph": {"@id": "https://id.kb.se/term/kssb/7", "@type": "ConceptScheme", "notation": "kssb/7"}}, {"@graph": {"birthYear": "1925", "givenName": "Aleksandr Sergeevi\u010d", "familyName": "Kan", "@id": "http://127.0.0.1:5000/some?type=Person&familyName=Kan&givenName=Aleksandr%20Sergeevi%C4%8D&birthYear=1925", "@type": "Person"}}, {"@graph": {"@id": "http://127.0.0.1:5000/some?type=Concept&focus.type=Person&focus.name=Karl&focus.numeration=XII%2C&focus.qualifyingNote=kung%20av%20Sverige%2C&focus.birthYear=1682&focus.deathYear=1718", "@type": "Concept", "focus": {"@id": "http://127.0.0.1:5000/some?type=Person&name=Karl&numeration=XII%2C&qualifyingNote=kung%20av%20Sverige%2C&birthYear=1682&deathYear=1718"}}}, {"@graph": {"name": "Karl", "@id": "http://127.0.0.1:5000/some?type=Person&name=Karl&numeration=XII%2C&qualifyingNote=kung%20av%20Sverige%2C&birthYear=1682&deathYear=1718", "birthYear": "1682", "deathYear": "1718", "@type": "Person", "numeration": "XII,", "qualifyingNote": ["kung av Sverige,"]}}, {"@graph": {"title": "Karolinska f\u00f6rbundets \u00e5rsbok", "issn": "0348-9833", "describedBy": [{"@id": "http://libris.kb.se/bib/8261779"}], "part": ["2000, s. [215]-217"], "@id": "http://127.0.0.1:5000/some?type=Aggregate&title=Karolinska%20f%C3%B6rbundets%20%C3%A5rsbok&issn=0348-9833&describedBy.type=Record&describedBy.id=http%3A%2F%2Flibris.kb.se%2Fbib%2F8261779&describedBy.controlNumber=8261779&part=2000%2C%20s.%20%5B215%5D-217", "@type": "Aggregate"}}, {"@graph": {"@id": "http://libris.kb.se/bib/8261779", "@type": "Record", "controlNumber": "8261779"}}]}
```
Results in error:
```
12:33:55.933 [1426656555@qtp-95319724-0] INFO  whelk.rest.api.ConverterAPI - Constructed document. Converting to null
java.lang.NullPointerException: Cannot get property 'marc:publicationStatus' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:256)
	at org.codehaus.groovy.runtime.dgm$241.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at whelk.converter.marc.FoldLinkedPropertyStep.unmodify(MarcFramePostProcStep.groovy:66)
	at whelk.converter.marc.MarcFramePostProcStep$unmodify.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at whelk.converter.marc.MarcConversion$_revert_closure12.doCall(MarcFrameConverter.groovy:380)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
	at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at whelk.converter.marc.MarcConversion.revert(MarcFrameConverter.groovy:379)
	at whelk.converter.marc.MarcConversion$revert$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at whelk.converter.marc.MarcFrameConverter.runRevert(MarcFrameConverter.groovy:93)
	at whelk.converter.marc.MarcFrameConverter$runRevert$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at whelk.converter.marc.JsonLD2MarcConverter.convert(JsonLD2MarcConverter.groovy:27)
	at whelk.converter.FormatConverter$convert.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at whelk.converter.marc.JsonLD2MarcXMLConverter.convert(JsonLD2MarcXMLConverter.groovy:32)
	at whelk.converter.FormatConverter$convert.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at whelk.rest.api.ConverterAPI.doPost(ConverterAPI.groovy:41)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at whelk.AuthenticationFilter.doFilter(AuthenticationFilter.java:64)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

**Comment by niklasl** [comment]
The revert function of marcframe works with this. Try the following locally:

1. Save the data above to a file, e.g.: `/tmp/revert-test.jsonld`
2. Run: `gradle runMarcFrame -Dargs="revert /tmp/revert-test.jsonld"`

Does this work? If so, the error occurs somewhere between the rest wrapper and MarcFrameConverter. (If, not, we're not running the same version of whelk-core.)
