### ISSUE TITLE
Deleted record is not deleted from elasticsearch index

### ISSUE THREAD

**Issue by sweco-semhul** [libris/librisxl#130]
When deleting a record by sending DELETE request to http://localhost:8180/zh9dnv790bgs3rq
The record is deleted from PostgreSQL storage but not from elasticsearch, seams to be related to the following stacktrace:

```
12:39:14.278 [1426656555@qtp-95319724-0] DEBUG whelk.component.PostgreSQLComponent - loadFromSql [1:zh9dnv790bgs3rq] (SELECT id,data,manifest,created,modified,deleted FROM lddb WHERE id= ?)
12:39:14.279 [1426656555@qtp-95319724-0] DEBUG whelk.component.PostgreSQLComponent - Got connection.
12:39:14.286 [1426656555@qtp-95319724-0] DEBUG whelk.rest.api.Crud - User is: [username:test, email:tratten@kb.se, authorization:[[sigel:S, ill:false, kat:true, reg:false, xlreg:true], [sigel:SEK, ill:false, kat:true, reg:false, xlreg:true], [sigel:SEK2, ill:false, kat:false, reg:false, xlreg:true], [sigel:SEK3, ill:false, kat:true, reg:false, xlreg:false], [sigel:SEK4, ill:true, kat:true, reg:false, xlreg:false]]]
12:39:14.286 [1426656555@qtp-95319724-0] DEBUG whelk.rest.api.Crud - Removing resource at zh9dnv790bgs3rq
12:39:14.286 [1426656555@qtp-95319724-0] DEBUG whelk.component.PostgreSQLComponent - Creating tombstone record with id zh9dnv790bgs3rq
12:39:14.287 [1426656555@qtp-95319724-0] DEBUG whelk.component.PostgreSQLComponent - Saving zh9dnv790bgs3rq
12:39:14.288 [1426656555@qtp-95319724-0] DEBUG whelk.Document - Finding identifiers in [@type:Tombstone]
12:39:14.290 [1426656555@qtp-95319724-0] DEBUG whelk.component.PostgreSQLComponent - Trying to save a version of zh9dnv790bgs3rq with checksum 2e3a5c8087e62baae5f3ae970ef56b87. Modified: Wed Jun 22 12:39:14 CEST 2016
12:39:14.293 [1426656555@qtp-95319724-0] DEBUG whelk.component.PostgreSQLComponent - Already had same version
12:39:14.294 [1426656555@qtp-95319724-0] DEBUG whelk.component.PostgreSQLComponent - [store] Closed connection.
12:39:14.294 [1426656555@qtp-95319724-0] DEBUG whelk.component.ElasticSearch - Deleting object with identifier zh9dnv790bgs3rq.
12:39:14.297 [1426656555@qtp-95319724-0] ERROR whelk.rest.api.Crud - Something went wrong
org.elasticsearch.transport.ActionNotFoundTransportException: No handler for action [indices:data/write/delete/by_query]
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:237) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.5.Final.jar:na]
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.5.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_25]

```

**Comment by mskold** [comment]
Not a bug. Delete by query was removed in ES 2.0 and now needs to be added as a plugin.
$ bin/plugin install delete-by-query
